---
-  hosts: local
   become: true
   become_user: root
   connection: local
   tasks:
   -  name: Deploying Grafana and Prometheus server containers
      shell: sh Role/grafana-server/setup.sh
      tags: local
      
   -  name: Deploying node-exporter locally
      command: sh Role/node-exporter/setup.sh
      tags: local
