version: '3'
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - "/opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "/opt/prometheus/data:/prometheus"
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=/run/secrets/grafana_password
    volumes:
      - /opt/grafana:/etc/grafana/provisioning/datasources
