global:
    scrape_interval: "15s"
    evaluation_interval: "15s"
scrape_configs:
  - job_name: local-server
    metrics_path: /metrics
    static_configs:
    - targets: ["localhost:9100"]
##Template for adding external targets    
#  - job_name: server-1
#    metrics_path: /metrics
#    static_configs:
#    - targets: ["server1-ip:9100"]    
